const createIssue = require('./create-issue.js');
const createProject = require('./create-project.js');
const getIssueByID = require('./get-issue-by-id.js');
const deleteIssueByID = require('./delete-issue-by-id.js');
const getIssues = require('./get-issues.js');
const getTransitions = require('./get-transitions.js');
const getUsers = require('./get-users.js');
const updateStatus = require('./update-status.js');
const getProjects = require('./get-projects.js')
const updateIssue = require("./update-issue.js")
const jiraRoutes = require('./src/routes/jiraRoutes.js');
const express = require('express');

const createIssueAndUpdate = async () => {
  const issueType = "Task"
  const summary = 'Task 1!';
  const description = 'Test!!'

  const issueKey = await createIssue('KAN', issueType, summary, description);
  console.log(`Created issue with key: ${issueKey}`);

  // Notes about statusID: statusID corresponds to " 11 == "To Do", 21=="In Progress", 31=="In Review", 41=="Done"

  const statusID = '21'

  // Add issueKey you want to update. This will be the key which we autogenerated from the issue above.
  const update = await updateStatus(issueKey, statusID);
  console.log(update)
}

const updateIssue1 = async () => {
  const updated = updateIssue({
    issueKey: "KAN-2",
    summary: "Updated task title",
    description: "New description here",
    assignee: "712020:38911630-0d80-4b25-aaf3-6b5bf442efd4", // Jira accountId
    labels: ["backend", "urgent"],
  });
}

//This will output the most recent projects
const getRecentProjects = async () => {
  const recentProjects = await getProjects();
  console.log(recentProjects)
}

//This will list all issues for a project
const getIssuesFunc = async () => {
  const issues = await getIssues();
  console.log(issues)
}

// This will list all transitions for a project.
const getTransitionsFunc = async (issueKey) => {
  const transitions = await getTransitions(issueKey);
  console.log(transitions)
}

const getIssueByIDFunc = async (issueKey) => {
  const issue = await getIssueByID(issueKey);
  console.log(issue)
}

const deleteIssueByIDFunc = async (issueKey) => {
  const issue = await deleteIssueByID(issueKey);
  console.log(issue)
}

const updateStatusFunc = async (issueKey, statusID) => {
  const status = await updateStatus(issueKey, statusID);
  console.log(status)
}

// This will list all users
const getUsersFunc = async () => {
  const users = await getUsers();
  console.log(users)
}


// Create a new project
// console.log(createProject("AK"));

// Step 1, get user account ID to be able to assign a new project to a user
// Get users - needed to get the leadAccountID to be able to create a project!
// getUsersFunc();

// Step 2, add the accountID to the env file, save the file and run source .env and then 
// uncomment the function call below to create a project, create an issue in that project,
// and mark that issue as in progress
// createIssueAndUpdate();

// Step 3, uncomment the function call below to get issues to see the newly created issue
// getIssuesFunc();

// Step 4, uncomment the function call below to get issues to see the newly created project
// Get recent projects
// getRecentProjects();

// Optional -- uncomment the function call below to get an issue by ID
// getIssueByIDFunc('KAN-1')

// Optional -- uncomment the function call below to get transitions of a newly created project
// Get transitions - needed to see how to update the status of an issue
// getTransitionsFunc('KAN-2')

// updateStatusFunc('KAN-1', '31')

// Optional -- uncomment the function call below to delete an issue by ID
// deleteIssueByIDFunc('KAN-6');

// updateIssue1()


const app = express();
app.use(express.json());

app.use('/api/jira', jiraRoutes);

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));